/*
 * generated by Xtext 2.22.0
 */
package jonasmohr.mdsd2021;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CMSdslStandaloneSetup extends CMSdslStandaloneSetupGenerated {

	public static void doSetup() {
		new CMSdslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
